### ISSUE TITLE
Persist custom path inventory creation not working with persist  after release 2.0.0

### ISSUE THREAD

**Issue by rohitthakur2590** [redhat-cop/network.base#41]
Persist custom path inventory creation not working with persist  after release 2.0.0

**Comment by Roiki11** [comment]
The problem is in the write_to_file.yaml file, the copy and file tasks don't include the **inventory_direcrory** variable defined in the first task. You need to prepend that variable to the following tasks and it works.

And you should add _sort_keys=false_ to the to_nice_yaml filter so it outputs syntax correct yaml. Otherwise it will mess the output.

Edit: deploy is also affected by missing the **inventory_directory** variable.
